baseURL = 'http://ancientink.de/'
languageCode = 'de-DE'
title = 'Ancientink'
theme = 'hugo-theme-terminal'
paginate = 5

[params]
  themeColor = "orange"
  showLanguageSelector = true
  fullWidthTheme = false
  centerTheme = true
  logoText = "Ancientink"
  logoHomeLink = "/"

[languages]
  [languages.en]
    title = "Ancientink"
    copyright = ""

    [languages.en.params.logo]
      logoText = "Ancientink"
      logoHomeLink = "/"
