baseURL = 'https://ancientink.de/'
languageCode = 'de-DE'
title = 'Ancientink'
theme = 'hugo-theme-terminal'

[params]
  themeColor = "green"
  showMenuItems = 2
  showLanguageSelector = true
  fullWidthTheme = true
  centerTheme = true